# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(1, 'Happy'), (2, 'Bad'), (3, 'Usually'), (4, 'Annoyed'), (5, 'Anger')]),
        ),
    ]
